Agence_Immobiliere_Symfony5/src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min = 5)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min = 10, max = 400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={ "default" : false })
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;
    
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="fileName")
     * 
     * @var File|null
     * @Assert\Image(mimeTypes = {"image/jpeg", "image/png"})
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string|null
     */
    private $fileName;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;
    
    public function __construct(){
        
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    
    public function getSlug(): ?string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
    
    public function getFormattedPrice(): string
    {

        return number_format($this->price,0,'',' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    
    public function getHeatType(): ?string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }
    
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        
        if ($this->imageFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }
        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setFileName(?string $fileName): Property
    {
        $this->fileName = $fileName;
        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

Agence_Immobiliere_Symfony5/src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use App\Entity\Option;

class PropertyType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add('title')
                ->add('description')
                ->add('surface')
                ->add('rooms')
                ->add('bedrooms')
                ->add('floor')
                ->add('price')
                ->add('heat', ChoiceType::class, [
                    'choices' => $this->getChoices()
                ])
                ->add('options', EntityType::class, [
                    'class' => Option::class,
                    'required' => false,
                    'choice_label' => 'name',
                    'multiple' => true
                ])
                ->add('imageFile', FileType::class, [
                    'required' => false
                ])
                ->add('city')
                ->add('address')
                ->add('postal_code')
                ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    public function getChoices() {

        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v) {
        $output[$v] = $k;
        }
        return $output;
    }

}

Agence_Immobiliere_Symfony5/src/Controller/PropertyController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\Contact;
use App\Form\ContactType;
use App\Notification\ContactNotification;

class PropertyController extends AbstractController {

    /**
     *
     * @var PropertyRepository 
     */
    private $repository;

    public function __construct(PropertyRepository $repository) {
        $this->repository = $repository;
    }

    /**
     * @Route("/biens", name="property.index")
     */
    public function index(PaginatorInterface $paginator, Request $request) {

        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $property = $paginator->paginate($this->repository->findAllVisibleQuery($search), $request->query->getInt('page', 1), 12);
        return $this->render('property/index.html.twig', [
                    'properties' => $property,
                    'current_menu' => 'properties',
                    'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug":"[a-z0-9\-]*"})
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification) {

        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                        'id' => $property->getId(),
                        'slug' => $property->getSlug()], 301);
        }

        $contact = new Contact();
        $contact->setProperty($property);

        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $notification->notify($contact);
            $this->addFlash('success', 'Votre email a bien été envoyé');
            return $this->redirectToRoute('property.show', [
                        'id' => $property->getId(),
                        'slug' => $property->getSlug()]);
        }

        //$property = $this->repository->find($id);
        return $this->render('property/show.html.twig', [
                    'property' => $property,
                    'current_menu' => 'properties',
                    'form' => $form->createView()
        ]);
    }

}

Agence_Immobiliere_Symfony5/templates/property/_property.html.twig
<div class="card mb-4">
    {% if property.fileName %}
        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;" />
    {% else %}
        <img src="{{ "/images/properties/empty.jpg" | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;" />
    {% endif %}
    
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', { id:property.id , slug:property.slug }) }}">{{ property.title }}</a>
        </h5>
        <p class="card-text">
            {{ property.surface }} m² - {{ property.city }} ({{ property.postalCode }})
        </p>
        <div class="text-primary" style="font-size: 2rem; font-weight: bold;">
            {{ property.getFormattedPrice }} €
        </div>
    </div>
</div>

Agence_Immobiliere_Symfony5/templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tout nos biens{% endblock %}

{% block body %}

    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4">
        <h1>Voir tous nos biens</h1>
        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {% include 'property/_property.html.twig' %}
                </div>
            {% endfor %}
        </div>

        <div class="navigation">
            {{ knp_pagination_render(properties, '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig') }}
        </div>
    </div>
{% endblock%}

Agence_Immobiliere_Symfony5/templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ property.title }} {% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">

            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}

            {% if not form.vars.valid %}
                <div class="alert alert-danger">
                    ERROR: Remplissage du formulaire contact est erroné
                </div>
            {% endif %}

            <div class="row">
                <div class="col-md-8">
                    {% if property.fileName %}
                        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto;" />
                    {% else %}
                        <img src="{{ "/images/properties/empty.jpg" | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto;" />

                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
                    <div class="text-primary" style="font-size: 4rem; font-weight: bold;">
                        {{ property.getFormattedPrice }} €
                    </div>
                    <a href="#" class="btn btn-primary" id="contactButton" {% if form.vars.submitted %}style="display: none;"{% endif %}>Contactez l'agence</a>
                    <div id="contactForm" class="mt-4"{% if not form.vars.submitted %}style="display: block;"{% endif %}>
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col-md-6">
                                {{ form_row(form.firstName) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_row(form.lastName) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {{ form_row(form.phone) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_row(form.email) }}
                            </div>
                        </div>
                        {{ form_rest(form) }}
                        {{ form_end(form) }}

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <p>
            {{ property.description | nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristique</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
                <div class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item">{{ option.name }}</li>
                        {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock%}